main:
	g++ -W -Wall -Wno-unused-parameter -pthread -lstdc++fs --std=c++17 lib/net_aux.cpp node_one.cpp -o node_one
	g++ -W -Wall -Wno-unused-parameter -pthread -lstdc++fs --std=c++17 lib/net_aux.cpp node_two.cpp -o node_two
