main:
	g++ -W -Wall -pthread -lstdc++fs --std=c++17 lib/net_aux.cpp captor/node_captor.cpp -o captor/node_captor
	g++ -W -Wall -pthread -lstdc++fs --std=c++17 lib/net_aux.cpp captorTwo/node_captor.cpp -o captorTwo/node_captor
	g++ -W -Wall -pthread -lstdc++fs --std=c++17 lib/net_aux.cpp collector/node_collector.cpp -o collector/node_collector